version: "3.8"

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "8080:8080"

  hugo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1313:1313"
